nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Keyword score
            description: Calculate word popularity on GitHub!
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
